-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 03, 2021 at 01:07 PM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 8.0.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `news`
--

-- --------------------------------------------------------

--
-- Table structure for table `loginattempt`
--

CREATE TABLE `loginattempt` (
  `id` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `status` int(1) NOT NULL,
  `time_attempt` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `loginattempt`
--

INSERT INTO `loginattempt` (`id`, `username`, `status`, `time_attempt`) VALUES
(1, '123@gmail.com', 1, '2021-05-30 21:07:15'),
(2, '123@gmail.com', 1, '2021-05-30 21:09:30'),
(3, '123@gmail.com', 1, '2021-05-30 21:16:02'),
(4, '123@gmail.com', -1, '2021-05-31 19:13:50'),
(5, '123@gmail.com', 1, '2021-05-31 19:15:09'),
(6, '123@gmail.com', -1, '2021-06-01 12:43:21'),
(7, 'akahle@gmail.com', 1, '2021-06-01 12:44:22'),
(8, '123@gmail.com', 1, '2021-06-01 15:39:51'),
(9, '123@gmail.com', -1, '2021-06-01 19:12:27'),
(10, '123@gmail.com', 1, '2021-06-02 18:55:34'),
(11, '123@gmail.com', -1, '2021-06-02 21:02:15'),
(12, '123@gmail.com', 1, '2021-06-02 21:25:58'),
(13, '123@gmail.com', -1, '2021-06-03 13:04:01');

-- --------------------------------------------------------

--
-- Table structure for table `newsdb`
--

CREATE TABLE `newsdb` (
  `item_id` varchar(60) NOT NULL,
  `view_count` int(10) NOT NULL,
  `img` text NOT NULL,
  `item_type` text NOT NULL,
  `source` text NOT NULL,
  `author` text NOT NULL,
  `descr` text NOT NULL,
  `url` text NOT NULL,
  `content` text NOT NULL,
  `title` text NOT NULL,
  `date_uploaded` date NOT NULL,
  `time_uploaded` time NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `newsdb`
--

INSERT INTO `newsdb` (`item_id`, `view_count`, `img`, `item_type`, `source`, `author`, `descr`, `url`, `content`, `title`, `date_uploaded`, `time_uploaded`) VALUES
('1003197', 0, 'https://i.cbc.ca/1.6043873.1622204788!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_620/dino-colalillo-edgewood-furniture.jpg', 'story', 'CBC News', '', 'The federal government slapped tariffs on certain types of furniture made in Vietnam and China earlier this month, and the impact on consumers and retailers has been dramatic, with some items now costing almost four times what they did before.', 'https://www.cbc.ca/news/business/furniture-tariffs-1.6043863', 'With more than 40 years of experience, Love Dodd of Victoria thought he had seen everything the furniture business could throw at him.\r\nBut even he almost jumped out of his chair when he saw the size… [+8231 chars]', 'Thinking of buying a new couch? The price may have just quadrupled - CBC.ca', '2021-05-31', '03:42:02'),
('1074768', 0, 'https://www.enca.com/sites/default/files/styles/facebook/public/2020-03/web_photo_sacorona2_220320.jpg?h=199d8c1f&itok=TKWWyDdu', 'story', 'eNCA', '', 'A jump in new coronavirus cases as criticism of the country`s slow vaccine rollout is continuing.', 'https://www.enca.com/news/covid-19-sa-5782-new-cases-110-deaths-recorded', 'JOHANNESBURG - The COVID-19 positivity rate has reached a record high of 12.7 percent, indicating the country is moving into the third wave.\r\nIt`s also recorded the highest number of new infections i… [+582 chars]', 'COVID-19 in SA: 110 deaths, 5782 new cases recorded - eNCA', '2021-06-03', '04:25:00'),
('1137540', 0, 'https://image-prod.iol.co.za/resize/650x366/For-the-first-time-since-the-peak-of-second-Covid-19-wave-in-December-South-Africa-has-breached-the-5000-mark-for-daily-new-infections-Photographer-Ayanda-Ndamane-African-News-Agency-ANA?source=https://xlibris.public.prod.oc.inl.infomaker.io:8443/opencontent/objects/5da474b8-9922-5237-ac97-daac5542c8d0&operation=CROP&offset=0x110&resize=2396x1348', 'story', 'IOL', 'Lee Rondganger', 'For the first time since the peak of second Covid-19 wave in December, South Africa has breached the 5000 mark for daily new infections.', 'https://www.iol.co.za/news/third-wave-sa-breaches-5000-new-covid-19-infections-as-gauteng-surges-ahead-57f56354-2200-4bc1-8cde-72010a48f4cd', 'Durban - For the first time since the peak of second Covid-19 wave in December, South Africa has breached the 5000 mark for daily new infections.\r\nThis was the startling data that emerged on Wednesda… [+2146 chars]', 'Third Wave: SA breaches 5000 new Covid-19 infections as Gauteng surges ahead - IOL', '2021-06-03', '05:59:16'),
('1194010', 4, 'https://www.sportsnet.ca/wp-content/uploads/2021/05/islanders-game-2.jpg', 'story', 'Sportsnet.ca', 'Iain MacIntyre', 'Physical would be understating it. The Boston Bruins and New York Islanders are engaged in a heavyweight slugfest, two formidable teams going head-to-head in what`s shaping up to be a test of survival.', 'https://www.sportsnet.ca/nhl/article/islanders-take-game-2-clash-bruins-shapes-test-survival/', 'The New York Islanders and Boston Bruins played a fantastic playoff game Monday night, and Auston Matthews and Mitch Marner didnt score in that one either.\r\nBut Casey Cizikas did.\r\nThe veteran energy… [+7043 chars]', 'Islanders take Game 2 as clash with Bruins shapes up to be test of survival - Sportsnet.ca', '2021-06-01', '05:38:00'),
('1196737', 0, 'https://images.glaciermedia.ca/polopoly_fs/1.24325184.1622521217!/fileImage/httpImage/image.jpg_gen/derivatives/facebookogimage_560_292/tc-250765-web-05312021-covid-update-1-jpg.jpg', 'story', 'Times Colonist', 'Cindy E. Harnett', 'A case of a rare blood clot linked to the AstraZeneca vaccine — the province’s third — has been reported in Island Health.The man, who in his 30s, is receiving treatment and recovering in hospital, . . .', 'https://www.timescolonist.com/news/local/b-c-s-third-case-of-rare-covid-vaccine-related-blood-clot-reported-in-island-health-1.24325181', 'A case of a rare blood clot linked to the AstraZeneca vaccine the provinces third has been reported in Island Health.\r\nThe man, who in his 30s, is receiving treatment and recovering in hospital, prov… [+3077 chars]', 'B.C.`s third case of rare COVID vaccine-related blood clot reported in Island Health - Times Colonist', '2021-05-31', '11:01:00'),
('1203446', 1, 'https://i2.wp.com/nasilemaktech.com/wp-content/uploads/2021/05/Arm_Computex_2021_Event_Banner_1140x695.png', 'story', 'Nasilemaktech.com', '', 'Arm`s keynote at COMPUTEX 2021 is not purely about product announcement or updates to the company, it was about sending a message delivered in 4 major points. We`ve round it up and summarized it here.', 'https://nasilemaktech.com/computex-2021-arm-1st-keynote-summary/', 'Arm’s keynote at COMPUTEX 2021 is not purely about product announcement or updates to the company, it was about sending a message delivered in 4 major points. We’ve round it up and summarized it here… [+1775 chars]', 'Simon Segars delivers 4 key points during Arm`s 1st keynote at COMPUTEX 2021 - Nasi Lemak Tech', '2021-06-01', '02:00:51'),
('1297897', 0, 'https://i.cbc.ca/1.6049832.1622640130!/fileImage/httpImage/image.JPG_gen/derivatives/16x9_620/covid-19-vaccination-sticker.JPG', 'story', 'CBC News', '', 'The heads of Manitoba`s COVID-19 vaccination task force are set to give an update on Wednesday, just as the province has further expanded eligibility for second doses.', 'https://www.cbc.ca/news/canada/manitoba/covid19-vaccination-update-manitoba-reimer-botha-1.6049837', 'The heads of Manitoba`s COVID-19 vaccination task force are set to give an update on Wednesday, just as the province has further expanded eligibility for second doses.\r\nCBC Manitoba will live stream … [+1174 chars]', 'Task force to give COVID-19 vaccination update for Manitoba - CBC.ca', '2021-06-02', '02:02:04'),
('1481364', 0, 'https://i.kinja-img.com/gawker-media/image/upload/c_fill,f_auto,fl_progressive,g_center,h_675,pg_1,q_80,w_1200/8f3bb112fecff52a0839d387a7f9d2ef.jpg', 'story', 'Gizmodo.com', 'Florence Ion', 'More than 60 new laptops are coming this year.', 'https://gizmodo.com/intel-beefs-up-11th-gen-laptop-processors-with-better-g-1846985639', 'Intel revealed new additions to its 11th-gen mobile processor lineup as part of this years virtual Computex show. The processors are based on Intels Evo platform and feature integrated Iris Xe graphi… [+3312 chars]', 'Intel Beefs Up 11th-Gen Laptop Processors With Better Graphics and Faster Wifi - Gizmodo', '2021-05-31', '03:42:03'),
('1592613', 0, 'https://i.cbc.ca/1.6050046.1622647927!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_620/nova-scotia-phase-1-day-one-bars.jpg', 'story', 'CBC News', '', 'Premier Iain Rankin and Chief Medical Officer of Health Dr. Robert Strang will hold a COVID-19 briefing Wednesday, the first day of the province`s phased reopening. The briefing is scheduled to begin at 3 p.m.', 'https://www.cbc.ca/news/canada/nova-scotia/nova-scotia-covid-update-june-2-2021-1.6049756', 'People headed to sun-soaked patios and lined up for haircuts in Halifax on Wednesday on the first day following Nova Scotia`s month-long lockdown.\r\nPhase 1 of Nova Scotia`s reopening plan started Wed… [+3137 chars]', 'Nova Scotians head to patios, line up for haircuts as province emerges from lockdown - CBC.ca', '2021-06-02', '03:53:35'),
('167990', 0, 'https://imagesvc.meredithcorp.io/v3/mm/image?q=85&c=sc&poi=%5B1040%2C293%5D&w=2000&h=1000&url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2021%2F03%2F31%2FMare-of-Easttown.jpg', 'story', 'Entertainment Weekly', 'Joey Nolfi', 'The Oscar winner says she was determined to make the grizzled detective look as real and hardened as possible.', 'https://ew.com/tv/kate-winslet-mare-of-easttown-sex-scene/', 'The woman behind HBO`s limited seriesMare of Easttownwas willing to bare it all for the critically lauded murder-mystery show.\r\nIn a New York Times interview published hours after Sunday`s shocking s… [+1957 chars]', 'Kate Winslet didn`t let `Mare of Easttown` crew cut her `bulgy bit of belly` from sex scene - Entertainment Weekly News', '2021-05-31', '11:05:00'),
('1890979', 0, 'https://www.ctvnews.ca/polopoly_fs/1.5450359.1622497695!/httpImage/image.jpg_gen/derivatives/landscape_620/image.jpg', 'story', 'Ctvnews.ca', 'Josef Federman', 'Israel`s defense minister on Monday distanced himself from comments made by his military chief after Israel bombed a Gaza Strip high-rise housing an Associated Press office and other news outlets, saying the remarks were not meant to be taken literally.', 'https://www.ctvnews.ca/world/israeli-official-rolls-back-army-chief-comments-on-ap-gaza-1.5450342', 'JERUSALEM -- \r\nIsrael`s defense minister on Monday distanced himself from comments made by his military chief after Israel bombed a Gaza Strip high-rise housing an Associated Press office and other n… [+2400 chars]', 'Israeli official rolls back army chief comments on AP Gaza - CTV News', '2021-05-31', '09:49:00'),
('1962780', 0, 'https://cdn.24.co.za/files/Cms/General/d/11196/273e421c3743483c9758710eea17933c.jpg', 'story', 'News24', 'Jeanette Chabalala', 'The Public Protector`s office said it would initiate contempt proceedings against Health Minister Zweli Mkhize following his failure to honour a subpoena.', 'https://www.news24.com/news24/southafrica/news/just-in-public-protector-to-open-contempt-case-against-zweli-mkhize-for-failure-to-honour-subpoena-20210603', 'The Public Protector`s office said it would initiate contempt proceedings against Health Minister Zweli Mkhize following his failure to honour a subpoena.\r\n``Dr Mkhize was subpoenaed to give evidence … [+482 chars]', 'JUST IN | Public Protector to open contempt case against Zweli Mkhize for failure to honour subpoena - News24', '2021-06-03', '09:50:19'),
('2085543', 0, 'https://www.ctvnews.ca/polopoly_fs/1.1384579.1622644746!/httpImage/image.jpg_gen/derivatives/landscape_620/image.jpg', 'story', 'Ctvnews.ca', '', 'The United Nations Human Rights Office is calling on all levels of Canadian governments to investigate the deaths of Indigenous children at residential schools and to intensify efforts to find those who are missing.', 'https://www.ctvnews.ca/canada/un-seeks-full-probe-into-deaths-of-indigenous-students-at-residential-schools-1.5452917', 'The United Nations Human Rights Office is calling on all levels of Canadian governments to investigate the deaths of Indigenous children at residential schools and to intensify efforts to find those … [+2450 chars]', 'UN seeks full probe into deaths of Indigenous students at residential schools - CTV News', '2021-06-02', '02:37:00'),
('2146811', 0, 'https://www.castanet.net/content/2021/5/20210530160524-60b3f531ca795630d62aa0dejpeg_p3533423._p3533629.jpg', 'story', 'Castanet.net', '', 'Canadians are in no rush to head back to the office even as COVID-19 cases and deaths continue to decline across the country, a new survey suggests.', 'https://www.castanet.net/news/Poll/335558/If-given-the-choice-do-you-prefer-to-work-from-home-', 'Canadians are in no rush to head back to the office even as COVID-19 cases and deaths continue to decline across the country, a new survey suggests.\r\nA recent poll by Leger and the Association for Ca… [+850 chars]', 'If given the choice, do you prefer to work from home? - Castanet.net', '2021-06-01', '02:32:00'),
('2185667', 5, 'https://smartcdn.prod.postmedia.digital/nationalpost/wp-content/uploads/2021/05/Cherie-Wong-1.png', 'story', 'National Post', 'Jesse Snyder', 'China has sought to exert control over foreign politicians, academics, media, and other institutions in an attempt to grow its geopolitical position, the…', 'https://nationalpost.com/news/canada/china-exporting-their-authoritarianism-overseas-through-canadian-institutions-hong-kong-advocate-warns', 'China has sought to exert control over foreign politicians, academics, media, and other institutions in an attempt to grow its geopolitical position, the committee heard \r\nJesse Snyder\r\nCherie Wong, … [+7466 chars]', 'China `exporting their authoritarianism overseas` through Canadian institutions, Hong Kong advocate warns - National Post', '2021-06-01', '02:52:32'),
('2272280', 0, 'https://lh3.googleusercontent.com/1nBIvbVJFeI6iL4_Fg8AnfH4mLsEH8jziJuLmzGj-D-JPsUgl4TfJopncdobGXYOAOiqTYaaS12lbg-cOlEz_4STmN5rYv0XE7Eb5Js3ZjBS6Zk=s1000', 'story', 'Business Day', 'Nafisa Akabor', 'Xiaomi is a worthy replacement for Huawei. The Redmi Note 9T is a great budget phone with dual 5G SIM slots and full access to Google services', 'https://www.businesslive.co.za/fm/fm-fox/gimme/2021-06-03-tech-review-xiaomi-redmi-note-9t--affordable-dual-5g-handset/', 'The 6.53-inch handset has DotDisplay with the selfie cam on the top left, which offers an uninterrupted view of its 1080p HD display, making it suitable for viewing multimedia content or anything in … [+990 chars]', 'TECH REVIEW: Xiaomi Redmi Note 9T — affordable dual 5G handset - Financial Mail', '2021-06-03', '03:00:00'),
('2279178', 0, 'https://cdn.24.co.za/files/Cms/General/d/11018/80a49dff2f584818a145d5faa20519fc.jpg', 'story', 'News24', 'Mike Cohen', 'Plans by the ANC to amend the constitution to make it easier to expropriate land without paying for it have gone awry, because it failed to pin down sufficient support from other parties to push the changes through.', 'https://www.news24.com/fin24/economy/land-expropriation-plans-hit-major-stumbling-block-20210603', 'Plans by the ANC to amend the constitution to make it easier to expropriate land without paying for it have gone awry, because it failed to pin down sufficient support from other parties to push the … [+1981 chars]', 'Land expropriation plans hit major stumbling block - News24', '2021-06-03', '07:17:48'),
('2589985', 0, '', 'story', 'CanIndia News', '', 'After workers accused the company of censoring pro-Palestine content, Facebook-owned Instagram has tweaked its algorithms that will begin ranking original', 'https://www.canindia.com/instagram-tweaks-algorithm-after-censoring-pro-palestinian-content/', 'After workers accused the company of censoring pro-Palestine content, Facebook-owned Instagram has tweaked its algorithms that will begin ranking original and re-shared content equally.\r\nThe employee… [+1316 chars]', 'Instagram tweaks algorithm after `censoring` pro-Palestinian content - CanIndia News', '2021-05-31', '03:42:02'),
('2692610', 2, 'https://cdn.mobilesyrup.com/wp-content/uploads/2020/02/cogeco-9-scaled.jpg', 'story', 'MobileSyrup', '', 'Cogeco is receiving $31.7 million in funding to bring high-speed internet to the Haut-Saint-François RCM and the Val-Saint-François RCM in Quebec.', 'https://mobilesyrup.com/2021/06/02/cogeco-receives-funding-to-bring-high-speed-internet-to-two-regions-in-quebec/', 'Cogeco is receiving $31.7 million in funding to bring high-speed internet to the Haut-Saint-François RCM and the Val-Saint-François RCM in Quebec.\r\nThe project aims to bring connectivity to 4,340 hou… [+1116 chars]', 'Cogeco receives funding to bring high-speed internet to two regions in Quebec - MobileSyrup', '2021-06-02', '03:54:00'),
('2763670', 0, 'https://www.ctvnews.ca/polopoly_fs/1.5333569.1614872935!/httpImage/image.jpg_gen/derivatives/landscape_620/image.jpg', 'story', 'Ctvnews.ca', 'Rachel Lau', 'Starting this Saturday, Montrealers can walk into some clinics without an appointment to get vaccinated with either Pfizer or AstraZeneca.', 'https://montreal.ctvnews.ca/covid-19-walk-in-vaccine-clinics-now-offering-montrealers-1st-dose-pfizer-2nd-dose-astrazeneca-1.5452644', 'MONTREAL -- \r\nStarting this Saturday, Montrealers can walk into additional clinics without an appointment to get vaccinated.\r\nThe CIUSSS West-Central Montreal says it will offer a first dose of the P… [+753 chars]', 'COVID-19 walk-in vaccine clinics now offering Montrealers 1st dose Pfizer, 2nd dose AstraZeneca - CTV News Montreal', '2021-06-02', '11:27:00'),
('2815743', 0, 'https://www.aljazeera.com/wp-content/uploads/2021/05/2021-05-09T082910Z_1645306009_RC28CN9ZCJQJ_RTRMADP_3_HEALTH-CORONAVIRUS-PERU-GRIEF.jpg?resize=1200%2C630', 'story', 'Al Jazeera English', 'Al Jazeera', 'A government review finds that 180,764 died from the disease – almost triple the previous official figure of 69,342.', 'https://www.aljazeera.com/news/2021/5/31/peru-adjusts-covid-19-death-toll-to-over-180000', 'Peru has announced a sharp increase in its COVID-19 death toll, giving the South American nation the worst coronavirus-related death rate per capita in the world.\r\nIn an announcement from the preside… [+3369 chars]', 'Peru adjusts COVID-19 death toll, now highest per capita overall - Al Jazeera English', '2021-05-31', '11:26:15'),
('3023562', 0, '', 'story', 'Google News', '', '', 'https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9VS1EMm5XNjQ0bGPSAQA?oc=5', '', 'William Nylander Spoils Carey Price`s Shutout With Late Consolation Goal - SPORTSNET', '2021-06-01', '01:41:19'),
('3031190', 0, 'https://www.geo.tv/assets/uploads/updates/2021-05-31/352736_124037_updates.jpg', 'story', 'Www.geo.tv', 'Web Desk', 'Ed Sheeran and Courteney Cox joined forces to recreate the iconic “routine” from `Friends`', 'https://www.geo.tv/latest/352736-ed-sheeran-and-courteney-cox-recreate-the-iconic-routine-from-friends', 'British singer Ed Sheeran and American actor Courteney Cox have a special treat for all Friends fans.\r\nThe two stars joined forces to recreate the iconic routine from the classic nineties sitcom, ori… [+494 chars]', 'Ed Sheeran and Courteney Cox recreate the iconic routine from Friends - Geo News', '2021-05-31', '03:42:02'),
('3112277', 0, 'https://www.theglobeandmail.com/resizer/AEcmYNniITtCM-dJEEfFT53Sgys=/1200x0/filters:quality(80)/cloudfront-us-east-1.images.arcpublishing.com/tgam/XO5SRIRVLNOSXM4YUIHHPXXTH4.jpg', 'story', 'The Globe And Mail', '', 'Brookfield willing to pay up to $5.6-billion in cash', 'https://www.theglobeandmail.com/business/article-brookfield-hikes-hostile-takeover-bid-for-inter-pipeline-to-counter/', 'Brookfield Infrastructure Partners LP is raising its hostile takeover bid for Inter Pipeline Ltd. to $19.75 per share, topping the surprise offer Pembina Pipeline Corp. announced one day ago.\r\nBrookf… [+4625 chars]', 'Brookfield hikes hostile takeover bid for Inter Pipeline to counter Pembina`s surprise offer - The Globe and Mail', '2021-06-02', '12:33:50'),
('3136437', 0, 'https://lh3.googleusercontent.com/8BFM7suLnmGcdGvEgXY_B3hoHRdnDZ1UCBaF8jlKuZQ3nRpNo1bj9KL6deqmrYV5j5BN3msz2nsEOoUyShC2k8OXm7_wPFZuRjM_=s1000', 'story', 'SowetanLIVE', 'TimesLIVE', 'The health ministry announced that there were 5,782 new Covid-19 cases in the past 24 hours.', 'https://www.sowetanlive.co.za/news/south-africa/2021-06-03-gauteng-cases-surging-as-sa-records-5782-new-covid-19-infections-in-24-hours/', '', 'Gauteng cases surging as SA records 5,782 new Covid-19 infections in 24 hours - SowetanLIVE', '2021-06-03', '04:30:34'),
('337100', 2, 'https://www.theglobeandmail.com/resizer/YyW6Q7IqQoMHGtupUdOi-mZzOm8=/1200x0/filters:quality(80)/cloudfront-us-east-1.images.arcpublishing.com/tgam/42DC7JQLUBMYDFAOQMYJJR4GQ4.jpg', 'story', 'The Globe And Mail', 'The Canadian Press', 'Also, Quebec plans ‘normal’ return to school in fall without masks or class bubbles', 'https://www.theglobeandmail.com/canada/article-covid-19-news-today-stay-at-home-order-ends-in-ontario-but-most-other/', 'People walk past businesses on Spadina Avenue, in Toronto, on May 13, 2021. \r\nNathan Denette/The Canadian Press\r\nOntarios stay-at-home order lifts today, but most other public health measures are sta… [+5879 chars]', 'COVID-19 news today: Ontario stay-at-home order lifts, but most other public health restrictions remain - The Globe and Mail', '2021-06-02', '10:55:52'),
('3371742', 0, 'https://i.guim.co.uk/img/media/03296e4ddb5aec6151d5f135121aadd99d6812c0/0_420_5058_3034/master/5058.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=74658a44cd2edcb39c90bc3e10b7e24d', 'story', 'The Guardian', 'Guardian staff reporter', 'First Nations groups say giving children a proper burial will help families find closure following discovery of 215 bodies at Kamloops school', 'https://amp.theguardian.com/world/2021/jun/01/calls-to-find-all-canadas-indigenous-mass-graves-after-grim-residential-school-discovery', 'Indigenous groups in Canada are calling for a nationwide search for mass graves at residential school sites after the discovery of the remains of more than 200 children at one former school last week… [+4937 chars]', 'Calls to find all Canada’s Indigenous mass graves after grim residential school discovery - The Guardian', '2021-06-01', '01:34:00'),
('3565805', 0, 'https://lh3.googleusercontent.com/jqE1xYBpv-VzAculPIDdZmpembbqJtyhe6Jo2_NEF264skWWsTv8FwpMR51_DvkfkIHcGDn1TD765ArAkG3U4h08pLjkJs9fl5XlLHdccQtvSw=s1000', 'story', 'Business Day', 'Phuti Mpyane', 'The topless two-seater keeps you enthralled in a legitimate way', 'https://www.businesslive.co.za/bd/life/motoring/2021-06-03-porsche-718-spyder-is-a-stylish-rebel/', 'The Spyder experience and its auto box showed this car is not reserved for driving purists. It was exceedingly adept in some unlikely areas too, such as touring comfortably and averaging 7.9l/100km, … [+1681 chars]', 'Porsche 718 Spyder is a stylish rebel - Business Day', '2021-06-03', '03:08:00'),
('3579021', 0, 'https://images.indianexpress.com/2021/06/frog.jpg', 'story', 'The Indian Express', 'Dipanita Nath', 'The species is called Litoria mira, inspired by the Latin adjective mirum, which means surprised or strange, stemming from the scientist’s surprise in discovering an undescribed member of the predominately Australian Litoria genus of tree frogs.', 'https://indianexpress.com/article/explained/litoria-mira-frog-species-7338983/', 'A species of frog lives in the rainforests of New Guinea that appears to be made from chocolate just like the magical sweets popular in the wizarding world of J K Rowlings Harry Potter.\r\nAn Australia… [+2429 chars]', 'Explained: Meet the Litoria mira, real-life version of Harry Potter’s chocolate frogs - The Indian Express', '2021-06-01', '02:28:43'),
('3656726', 0, 'https://news.google.com/pageCount.htm?type=read&articleId=24829089', 'story', 'Swordstoday.ie', 'Jake Pearson', 'After two decades of research, NASA has released an image describing the ``violent energy`` that is not found at the center of our galaxy. CNN.The stunning', 'https://swordstoday.ie/a-new-nasa-photo-shows-the-violent-energy-of-our-galaxy-this-is-evidence-of-a-continuum-of-magnetic-field-reconnection-space/', 'After two decades of research, NASA has released an image describing the “violent energy” that is not found at the center of our galaxy. CNN.The stunning panorama was compiled using data from NASA’s … [+2038 chars]', 'A new NASA photo shows the ``violent energy`` of our galaxy / ``This is evidence of a continuum of magnetic field reconnection`` - Space - SwordsToday.ie', '2021-05-31', '03:42:02'),
('3894892', 0, 'https://lh3.googleusercontent.com/ZcUGHmfAD7QSAnZp4d-VO89sU1ESVwKuwnHNKNH6NOIUrCfkFW5WcTeigzloWWsEDbLetCvKVbOJKbON8Iwyf0flIyBWsm-wKnw=s1000', 'story', 'TimesLIVE', 'Andisiwe Makinana', 'President Cyril Ramaphosa says he has spoken to health minister Zweli Mkhize about the serious allegations of wrongdoing involving the alleged looting of state funds by Mkhize`s close associates.', 'https://www.timeslive.co.za/politics/2021-06-02-i-am-dealing-with-zweli-mkhize-and-he-is-co-operating-says-ramaphosa-on-digital-vibes-scandal/', '', 'I am dealing with Zweli Mkhize and he is co-operating, says Ramaphosa on Digital Vibes scandal - TimesLIVE', '2021-06-02', '02:28:29'),
('40074', 0, 'https://cdn.24.co.za/files/Cms/General/d/1700/1251e9007da446cd89f8038ed6c513de.jpg', 'story', 'News24', 'Nicole McCain', 'Four alleged illegal miners have died after a fight broke out at a Mpumalanga mine.', 'https://www.news24.com/news24/southafrica/news/4-suspected-zama-zamas-die-in-fight-at-mpumalanga-gold-mine-20210603', '<ul><li>The bodies of four suspected illegal miners have\r\nbeen recovered from a mine shaft.</li><li>The four allegedly died during a fight between\r\nillegal miners near Graskop over the weekend.</li><… [+1612 chars]', '4 suspected `zama zamas` die in fight at Mpumalanga gold mine - News24', '2021-06-03', '07:12:34'),
('4076132', 0, 'https://www.aljazeera.com/wp-content/uploads/2021/05/2021-05-31T193906Z_964628406_RC27RN9APJ90_RTRMADP_3_TENNIS-FRENCHOPEN.jpg?resize=1160%2C630', 'story', 'Al Jazeera English', 'Al Jazeera', 'Osaka withdrawing from the French Open following the bitter fallout from her decision to boycott all media activity.', 'https://www.aljazeera.com/news/2021/5/31/naomi-osaka-french-open-withdrawal-statement-in-full', 'Hey everyone, this isnt a situation I ever imagined or intended when I posted a few days ago. I think now the best thing for the tournament, the other players and my wellbeing is that I withdraw so t… [+1675 chars]', 'Naomi Osaka: French Open withdrawal statement in full - Al Jazeera English', '2021-05-31', '08:45:35'),
('4088776', 0, 'https://www.dailymaverick.co.za/wp-content/uploads/2021/06/Vearey-vs-Sitole.jpg', 'story', 'Daily Maverick', 'Marianne Thamm', 'A week after his swift dismissal by National Commissioner Khehla Sitole, former Western Cape Head of Detectives Jeremy Vearey has hit back in an exclusive interview with Daily Maverick, labelling the expeditious process to remove him as unprocedural.', 'https://www.dailymaverick.co.za/article/2021-06-03-a-defiant-jeremy-vearey-strikes-back-over-his-dismissal-by-saps-national-commissioner-khehla-sithole/', 'National Commissioner Khehla Sitole and Major-General Jeremy Vearey. (Photo: Gallo Images / Brenton Geach) \r\nOn Wednesday, Vearey said the expeditious process that had been triggered to fire him had … [+9584 chars]', 'A defiant Jeremy Vearey strikes back over his dismissal by SAPS National Commissioner Khehla Sitole - Daily Maverick', '2021-06-02', '11:29:28'),
('4151128', 0, 'https://basketball.realgm.com/images/nba/4.2/wiretap/photos/2006/Paul_Chris_phx_201230.jpg', 'story', 'Realgm.com', '', '', 'https://basketball.realgm.com/wiretap/262767/Monty-Williams-Planned-To-Sit-Chris-Paul-For-Game-4-But-Had-To-Trust-The-Player', 'Monty Williams originally planned to sit Chris Paul for the Phoenix Suns` 100-92 win over of the Los Angeles Lakers in Game 4.\r\n``He said, `Coach, let me start, and if you don`t think I`m looking like… [+540 chars]', 'Monty Williams Planned To Sit Chris Paul For Game 4 But `Had To Trust The Player` - RealGM.com', '2021-05-31', '03:42:03'),
('4227034', 0, 'https://lh3.googleusercontent.com/U1YoE1nqjr4DduKAeCVZawi3wgN1742pUT6Fz0AXnPAwWGa19Qibgl4K3cR-YRGC-Mbz4MkCmFaCLocnBgTg2UytHnsuKOKQzJQ=s1000', 'story', 'SowetanLIVE', 'Aphiwe Deklerk', 'The ANC has come out in support of the rotational rule for the election of the president of the Pan African Parliament.', 'https://www.sowetanlive.co.za/news/south-africa/2021-06-02-anc-supports-rotational-president-for-pan-african-parliament/', '', 'ANC supports rotational president for Pan African parliament - SowetanLIVE', '2021-06-02', '05:03:10'),
('4229853', 0, 'https://i.itbusiness.ca/wp-content/uploads/2018/01/ht_banner-hashtag-trending.jpg', 'story', 'ITBusiness.ca', 'Alex Coop', 'A lawsuit against Google gets class-action status, Iran bans cryptomining after rolling blackouts, and unredacted documents show Google made it hard to', 'https://www.itbusiness.ca/news/hashtag-trending-may-31-2021-600m-class-action-lawsuit-against-google-iran-bans-cryptomining-googles-collection-of-location-data/118286', 'A lawsuit against Google gets class-action status, Iran bans cryptomining after rolling blackouts, and unredacted documents show Google made it hard to keep location data private.\r\nIts all the biz/te… [+3018 chars]', 'Hashtag Trending, May 31, 2021 - $600M class-action lawsuit against Google; Iran bans cryptomining; Google’s collection of location data - ITBusiness.ca', '2021-05-31', '03:42:02'),
('4246653', 0, 'https://smartcdn.prod.postmedia.digital/nationalpost/wp-content/uploads/2021/06/2560px-Battleford_Industrial_School_Cemetery_Grave_Marker.jpg', 'story', 'National Post', 'Tristin Hopper', 'Indian Affairs refused to ship home children`s bodies because of the cost; it follows that most were buried on or near school grounds', 'https://nationalpost.com/news/canada/the-graves-were-never-a-secret-why-so-many-residential-school-cemeteries-remain-unmarked', 'Indian Affairs refused to ship home children`s bodies because of the cost; it follows that most were buried on or near school grounds \r\nTristin Hopper\r\nA grave marker denoting one of 72 graves at the… [+8768 chars]', 'The graves were never a secret: Why so many residential school cemeteries remain unmarked - National Post', '2021-06-02', '12:24:36'),
('4457535', 0, 'https://media.mg.co.za/wpmedia/2021/06/e9039b4e-elize-parker-vaccination-center-karl-bremmer-dh-1864-1024x683.jpg', 'story', 'Mail and Guardian', 'Eunice Stoltz', 'Elize Parker took matters into her own hands by doing a Covid-19 walk-in, after she didn’t get her confirmation SMS', 'https://mg.co.za/coronavirus-essentials/2021-06-03-frustrated-she-jumped-the-vaccination-queue/', 'Elize Parker, 61, was one of the first people to register for a Covid-19 vaccine in April, but after receiving a confirmation SMS from the government and Discovery Health, she did not receive any fur… [+2108 chars]', 'Frustrated, she jumped the vaccination queue - Mail and Guardian', '2021-06-03', '10:24:29'),
('4515014', 0, 'https://i.cbc.ca/1.4733413.1598369030!/fileImage/httpImage/image.jpg_gen/derivatives/16x9_620/mars-dust-storm.jpg', 'story', 'CBC News', '', 'Researchers from Western University in London, Ont., have found a unique subsurface ice feature in a location that would be optimal for future explorers of the Red Planet.', 'https://www.cbc.ca/news/science/glaciers-mars-arcadia-planitia-1.6044691', 'If humans are to truly become interplanetary settlers, we`re going to need to have access to water a lot of it. But loading it on a rocket would be heavy, and trying to escape Earth`s gravity with al… [+4296 chars]', 'Newly discovered glaciers on Mars may help humans settle on the Red Planet one day - CBC.ca', '2021-05-31', '03:42:02'),
('4643791', 0, 'https://a1.espncdn.com/combiner/i?img=%2Fphoto%2F2021%2F0602%2Fr861862_1296x729_16%2D9.jpg', 'story', 'ESPN', 'Greg Wyshynski', 'Who will win the North Division crown? We break it down position-by-position and make a pick.', 'https://www.espn.com/nhl/insider/story/_/id/31548148/2021-nhl-playoff-bracket-preview-winnipeg-jets-vs-montreal-canadiens-matchups-series-pick', 'With their thrilling Game 7 victory over the heavily favored Toronto Maple Leafs, the Montreal Canadiens earned a spot in the North Division final.\r\nThey`ll face the Winnipeg Jets, who had a signific… [+6653 chars]', '2021 NHL playoff bracket preview: Winnipeg Jets vs. Montreal Canadiens matchups, series pick - ESPN', '2021-06-02', '10:52:48'),
('4948011', 0, 'https://lh3.googleusercontent.com/18kSX3w9b1dKaxlHN5APXhPvegkyL7ePhYkvV9SfGycLn3fp-nsQHbnbDM5n5iHJACsM5_ygzKsGpRO1m1P8XiLP5wkPyQVCHhxr=s1000', 'story', 'TimesLIVE', 'Deepika Naidoo', 'Zodwa Wabantu is expanding her horizons with her latest business venture.', 'https://www.timeslive.co.za/tshisa-live/tshisa-live/2021-06-03-zodwa-wabantu-opens-mortuary--undertaker-services-company/', '', 'Zodwa Wabantu opens mortuary & undertaker services company - TimesLIVE', '2021-06-03', '05:00:00'),
('4982838', 0, 'https://images.thestar.com/raOgXQ3P_j0DNk3-KRTQerBl3hI=/1200x838/smart/filters:cb(1622409651785)/https://www.thespec.com/content/dam/thespec/news/hamilton-region/2021/05/30/covid-hamilton-latest-news/signs.jpg', 'story', 'TheSpec.com', '', 'Three deaths reported over weekend including a person in their 40s.', 'https://www.thespec.com/news/hamilton-region/2021/05/30/covid-hamilton-latest-news.html', 'Hamilton’s COVID-19 cases continued to drop over the weekend even as the city reported more deaths and cases of new variants.\r\nTwo deaths were reported on Sunday, one of a person in their 60s and ano… [+2319 chars]', 'COVID cases continue to drop as Hamilton reports new unknown variant - TheSpec.com', '2021-05-31', '03:42:03'),
('4984170', 0, 'https://s.yimg.com/os/creatr-uploaded-images/2021-06/fbb1bb20-c285-11eb-9a8f-cbb712015476', 'story', 'Yahoo Entertainment', 'Devindra Hardawar', 'Tesla`s refreshed Model S and X will run AMD`s RDNA 2 graphics.', 'https://ca.news.yahoo.com/teslas-new-model-s-x-rdna2-gpu-amd-030917029.html', 'The latest numbers on COVID-19 vaccinations in Canada as of 4:00 a.m. ET on Monday May 31, 2021. In Canada, the provinces are reporting 315,187 new vaccinations administered for a total of 23,471,446… [+8175 chars]', 'Tesla`s revamped Model S and X will feature RDNA 2 GPUs, AMD confirms - Yahoo Movies Canada', '2021-06-01', '03:18:43'),
('5143141', 0, 'https://mybroadband.co.za/news/wp-content/uploads/2021/04/AdaptIT.jpg', 'story', 'MyBroadband', 'https://www.facebook.com/mybroadband', 'Adapt IT’s independent board is accused of trying to push a narrow interest instead of getting the best offer for shareholders.', 'https://mybroadband.co.za/news/business/400027-fight-for-adapt-it.html', 'Adapt ITs independent board should promote competition between suitors to get the highest offer possible for Adapt IT shareholders, but instead it is playing favourites.\r\nThis is the view of Huge Gro… [+4088 chars]', 'Fight for Adapt IT - MyBroadband', '2021-06-03', '07:59:35'),
('5187704', 0, 'https://cdn.24.co.za/files/Cms/General/d/10951/3c102e1530a44a1992b9d9a1d4fb7f06.jpg', 'story', 'News24', 'Lwandile Bhengu', 'Health director-general Dr Sandile Buthelezi says the department expects the Food and Drug Administration (FDA) to make an announcement on the Johnson & Johnson (J&J) vaccine on Friday.', 'https://www.news24.com/news24/SouthAfrica/News/government-expecting-an-announcement-from-us-fda-on-jj-vaccine-delay-20210602', '<ul><li>There has been a delay in the rollout of the J&amp;J vaccine due to a lack of adherence to proper standards at a manufacturing plant in the US. </li><li>Health director-general Dr Sandile But… [+3509 chars]', 'Government expecting an announcement from US FDA on J&J vaccine delay - News24', '2021-06-02', '07:02:54'),
('5196835', 0, 'https://www.theglobeandmail.com/resizer/jZ1rIzebaYp2G-Blv4ZJXyMImzA=/1200x0/filters:quality(80)/cloudfront-us-east-1.images.arcpublishing.com/tgam/DCU5T7DZARK4XOKONMJXWT5H3Y.jpg', 'story', 'The Globe And Mail', '', 'As new brand ambassador for BetMGM, Gretzky said that the deal, reportedly worth US$3-million a year, will see him do pregame analysis on a studio hockey show similar to Inside the NBA', 'https://www.theglobeandmail.com/sports/article-wayne-gretzky-talks-about-his-move-to-broadcasting-and-partnering-with/', 'Former Edmonton Oilers great Wayne Gretzky in Toronto on Dec. 10, 2017. \r\nChristopher Katsarov/The Canadian Press\r\nWayne Gretzky is the new brand ambassador for BetMGM, a sportsbook with a growing fo… [+6863 chars]', 'Wayne Gretzky prepares for his next act in broadcasting and sports betting worlds - The Globe and Mail', '2021-06-02', '10:00:00'),
('5288829', 0, 'https://cdn.24.co.za/files/Cms/General/d/9815/1d4bfae0e2c2477489a89fe0760fdb84.jpg', 'story', 'News24', 'Lance Branquinho', 'President Cyril Ramaphosa knows cycling is good for the environment personal health. But what bike does he ride?', 'https://www.news24.com/ride24/news/cyril-went-bicycle-shopping-in-cape-town-20210603', '<ul><li>The President visited one of Cape Town`s most established bicycle shops, to do some shopping</li><li>Despite an impressive selection of Specialized bikes being on display, he chose a value mo… [+2669 chars]', 'PHOTOS | President Cyril Ramaphosa went bicycle shopping in Cape Town - News24', '2021-06-03', '07:20:18'),
('5326428', 0, 'https://images.daznservices.com/di/library/sporting_news/a4/8/sportingnews_blid1xj976d41uqjx0jd6x52p.png', 'story', 'Sporting News', 'Sporting News', 'Bukayo Saka has called his goal for England against Austria on Wednesday the biggest moment in his career thus far.', 'https://www.sportingnews.com/ca/soccer', '', 'Tau questions Kaizer Chiefs: Was the attitude not right? - Goal.com', '2021-06-03', '06:20:02'),
('5368194', 0, 'https://www.dailymaverick.co.za/wp-content/uploads/2021/06/372187749-scaled.jpg', 'story', 'Daily Maverick', 'Bloomberg', '(Bloomberg) --Microsoft Corp. will unveil a new version of its flagship Windows software on June 24, an update that Chief Executive Officer Satya Nadella has termed one of the “most significant” overhauls to the personal computer operating system this decade.', 'https://www.dailymaverick.co.za/article/2021-06-02-microsoft-to-unveil-new-windows-june-24-likely-for-fall-debut/', 'By Dina BassJun 2, 2021, 6:27 PMWord Count: 137The new software will include changes to the design, added opportunities for creators and developers via the Windows app store, and ways to more easily … [+453 chars]', 'Microsoft to Unveil New Windows June 24, Likely for Fall Debut - Daily Maverick', '2021-06-02', '07:39:49'),
('5407902', 0, 'http://ampvideo.bnnbloomberg.ca/polopoly_fs/1.1608681!/fileimage/httpImage/image.jpg_gen/derivatives/landscape_620/cracking-towers-stand-at-the-ruwais-refinery-and-petrochemical-complex-operated-by-abu-dhabi-national-oil-co-adnoc-in-al-ruwais-united-arab-emirates-on-monday-may-14-2018-adnoc-is-seeking-to-create-world-s-largest-integrated-refinery-and-petrochemical-complex-at-ruwais.jpg', 'story', 'BNNBloomberg.ca', 'Bloomberg News', 'Oil climbed for a second month as OPEC and its allies forecast that inventories will fall sharply this year if the group sticks to its plan.', 'http://ampvideo.bnnbloomberg.ca/oil-edges-higher-with-market-set-to-focus-on-opec-policy-meet-1.1610616', 'Oil climbed for a second month as OPEC and its allies forecast that inventories will fall sharply this year if the group sticks to its plan.\r\nFutures rose 0.9 per cent on Monday in New York, bringing… [+2218 chars]', 'Oil gains as OPEC+ forecasts crude stockpiles will drop sharply - BNN', '2021-05-31', '08:29:09'),
('5452705', 0, 'https://www.enca.com/sites/default/files/styles/facebook/public/2021-05/web_photo_zumacourt_230521.jpg?h=bc62b519&itok=Ms6sgid5', 'story', 'eNCA', '', 'The state says former President Jacob Zuma`s bid to remove state prosecutor Billy Downer should be rejected.', 'https://www.enca.com/news/downer-slams-zumas-special-plea', 'PIETERMARITZBURG - The state says former President Jacob Zuma`s bid to remove state prosecutor Billy Downer should be rejected.\r\nZuma applied for a special plea to have Downer removed from his corrup… [+390 chars]', 'Downer slams Zuma`s special plea - eNCA', '2021-06-03', '06:01:44'),
('5571022', 6, '', 'story', 'Google News', '', '', 'https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9S2VpUmIxYUdFb2vSAQA?oc=5', '', 'COVID-19: Manitoba doctors call for complete lockdown as hospitals reach breaking point - Global News', '2021-06-01', '02:30:08'),
('5634968', 0, 'https://www.cnet.com/a/img/YawaVihaR0nIiaxM6OyYWtQ6sfw=/1200x630/2021/06/02/192e09ba-2636-4f6c-9657-ce474ee559e3/annular-twitter.jpg', 'story', 'CNET', 'Eric Mack', 'Some early-rising eclipse chasers might also get to see the sun show off its rarely seen horns and ``shark fin`` too.', 'https://www.cnet.com/news/2021s-first-solar-eclipse-will-show-off-a-ring-of-fire-in-the-sky/', 'An annular solar eclipse in 2011.\r\nNASA\r\nOn the morning of June 10, the darkened new moon will slide in front of the sun, resulting in a partial solar eclipse that will be visible from big swaths of … [+2955 chars]', '2021`s first solar eclipse will show off a `ring of fire` in the sky - CNET', '2021-06-02', '01:36:57'),
('5696555', 0, 'https://www.sportsnet.ca/wp-content/uploads/2021/06/Mitch-Marner-Auston-Matthews-Jack-Campbell.jpg', 'story', 'Sportsnet.ca', 'Sportsnet Staff', 'Following Monday`s Game 7 loss to the Montreal Canadiens, a number of Toronto Maple Leafs players will meet with the media to discuss their play this season, the series with Montreal and what comes next.', 'https://www.sportsnet.ca/nhl/article/watch-live-maple-leafs-players-meet-media-playoff-elimination/', 'Following Monday’s Game 7 loss to the Montreal Canadiens, a number of Toronto Maple Leafs players will meet with the media to discuss their play this season, the series with Montreal and what comes n… [+33 chars]', 'Watch Live: Maple Leafs players meet media after playoff elimination - Sportsnet.ca', '2021-06-02', '02:01:00'),
('5698562', 0, 'https://smartcdn.prod.postmedia.digital/calgaryherald/wp-content/uploads/2021/05/PatioOpenings015-copy.jpg', 'story', 'Calgary Herald', 'Madeline Smith', 'Alberta’s reopening plan takes a step forward today, but city council heard Monday that there are still big questions looming for Calgary.', 'https://calgaryherald.com/news/local-news/nenshi-calls-for-massively-expanded-pop-up-vaccine-clinics-as-stage-1-reopening-starts-tuesday', 'Madeline Smith, Stephanie Babych\r\nChris Miller, husband of the co-owner, sets up the patio at the Seed N Salt on 4th Ave. S.W. for the June 1 openings in Calgary on Monday, May 31, 2021.Photo by Darr… [+7372 chars]', 'Nenshi calls for `massively expanded` pop-up vaccine clinics as Stage 1 reopening starts Tuesday - Calgary Herald', '2021-06-01', '01:41:15'),
('5727593', 0, 'http://cdn.primedia.co.za/primedia-broadcasting/image/upload/c_fill,h_437,w_700/qllopysqk6tw0piwnprk', 'story', 'EWN', 'Theto Mahlakoana', 'This followed the exoneration of the power utility’s group chief executive, Andre de Ruyter, by an independent investigation, which found that he was not guilty of racism, among other allegations.', 'https://ewn.co.za/2021/06/03/eskom-board-worried-over-wild-claims-by-employees-charged-with-ill-discipline', 'This followed the exoneration of the power utility’s group chief executive, Andre de Ruyter, by an independent investigation, which found that he was not guilty of racism, among other allegations.\r\n … [+1405 chars]', 'Eskom board worried over `wild` claims by employees charged with ill-discipline - Eyewitness News', '2021-06-03', '04:22:15'),
('5839169', 0, 'https://www.sportsnet.ca/wp-content/uploads/2021/05/clippers-mavs.jpg', 'story', 'Sportsnet.ca', 'Associated Press', 'Kawhi Leonard and Paul George combined to carry Los Angeles on the road again, and the Clippers are back in control of their first-round series with Dallas.', 'https://www.sportsnet.ca/nba/article/clippers-take-back-control-series-big-win-mavericks/', 'DALLAS — A little cat-and-mouse game between the coaches over the size of the lineups didn’t amount to much, as entertaining as it was early for another boisterous crowd in Dallas.\r\nThe big dogs of t… [+5178 chars]', 'Clippers take back control of series with big win over Mavericks - Sportsnet.ca', '2021-05-31', '03:42:02'),
('5909537', 0, 'https://techcentral.co.za/wp-content/uploads/2021/06/software-coding-developer-2156-1120.jpg', 'story', 'TechCentral', 'Duncan McLeod', 'Naspers-controlled Internet investment firm Prosus has agreed to acquire Stack Overflow, a platform used by software developers, for $1.8-billion.', 'https://techcentral.co.za/prosus-to-acquire-stack-overflow-for-1-8-billion/107755/', 'Naspers-controlled Internet investment firm Prosus has agreed to acquire Stack Overflow, a platform used by software developers, for US$1.8-billion (about R24.4-billion).\r\nAccording to Prosus, Stack … [+1898 chars]', 'Prosus to acquire Stack Overflow for $1.8-billion - TechCentral', '2021-06-02', '04:54:45'),
('594487', 0, '', 'story', 'Bloomberg', '', '', 'https://www.bloomberg.com/tosv2.html?vid=&uuid=451d2210-c45a-11eb-a6fb-bf738664ee61&url=L25ld3MvYXJ0aWNsZXMvMjAyMS0wNi0wMy8tY292aWQtemVyby1yaXNrcy1iZWluZy1jb3ZpZC1saW1iby1hbWlkLXNsb3ctdmFjY2luZS11cHRha2U=', 'To continue, please click the box below to let us know you`re not a robot.', '`Covid Zero` Risks Being `Covid Limbo` Amid Slow Vaccine Uptake - Bloomberg', '2021-06-03', '06:05:00'),
('5955125', 0, 'https://cdn.24.co.za/files/Cms/General/d/8770/395c367db3ce4807a785e49acbdbb0ff.jpg', 'story', 'News24', 'Kyle Cowan, Azarrah Karrim and Sipho Masando', 'In what is being described as a `startling` about-turn, Solly Tshitangano has now denied accusing André de Ruyter of racism after his widely publicised allegations that the CEO was targeting black-owned suppliers.', 'https://www.news24.com/news24/southafrica/investigations/eskomfiles/eskom-boss-de-ruyter-cleared-of-bizarre-startling-racism-abuse-of-power-claims-20210603', 'Axed Eskom procurement boss Solly Tshitangano`s allegations of racism against the power utility`s CEO, André de Ruyter, were ``wrong, egregious, false, baseless and lacking any substantiation``, an ind… [+129 chars]', 'Eskom boss De Ruyter cleared of `bizarre, startling` racism, abuse of power claims - News24', '2021-06-03', '03:25:39'),
('6042329', 0, 'https://i.cbc.ca/1.6047795.1622498570!/cpImage/httpImage/image.jpg_gen/derivatives/16x9_620/covid-ont-20210301.jpg', 'story', 'CBC News', '', 'The doctor who will guide Ontario`s path out of the COVID-19 pandemic is being described by colleagues and friends as a competent public health expert, straight shooter and excellent communicator.', 'https://www.cbc.ca/news/canada/toronto/ont-kieran-moore-1.6047776', 'The doctor who will guide Ontario`s path out of the COVID-19 pandemic is being described by colleagues and friends as a competent public health expert, straight shooter and excellent communicator.\r\nD… [+5542 chars]', '`He`ll give you a straight answer,` colleagues say of Ontario`s next top doctor - CBC.ca', '2021-05-31', '11:25:13'),
('6134388', 15, '', 'story', 'Google News', '', '', 'https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9aTNjTm5tUFFNU2vSAQA?oc=5', '', 'Trudeau says more help coming for residential school survivors - CBC News', '2021-06-01', '01:04:38'),
('6142919', 0, '', 'story', 'Google News', '', '', 'https://news.google.com/__i/rss/rd/articles/CBMiPWh0dHBzOi8vd3d3LmhlcmFsZC5jby56dy9taW5pbmctaW5kYWJhLXVuZGVyd2F5LWluLXZpYy1mYWxscy_SAUFodHRwczovL3d3dy5oZXJhbGQuY28uencvbWluaW5nLWluZGFiYS11bmRlcndheS1pbi12aWMtZmFsbHMvYW1wLw?oc=5', '', 'Mining Indaba underway in Vic Falls - The Herald', '2021-06-03', '12:25:20'),
('6154097', 0, 'https://image-prod.iol.co.za/resize/650x366/File-picture-Reuters-Gonzalo-Fuentes?source=https://xlibris.public.prod.oc.inl.infomaker.io:8443/opencontent/objects/babe7689-840c-5a6c-be76-b1fcbe511a33&operation=CROP&offset=0x148&resize=2822x1587', 'story', 'IOL', 'IANS', 'The global TWS hearables market managed to sustain its growth trend amid the pandemic as its sales grew 44 per cent Year-on-Year (YoY) in the first quarter of 2021, a report said.', 'https://www.iol.co.za/technology/gadgets/true-wireless-sales-up-by-44-in-q1-as-apple-leads-the-market-febf16a5-793c-4bd3-b9a0-ffbe546c0cc7', 'New Delhi - The global TWS hearables market managed to sustain its growth trend amid the pandemic as its sales grew 44 per cent Year-on-Year (YoY) in the first quarter of 2021, a report said on Wedne… [+1622 chars]', 'True wireless sales up by 44% in Q1 as Apple leads the market - IOL', '2021-06-03', '09:32:40'),
('6216588', 0, 'https://lh3.googleusercontent.com/3ecfCEjlgD5NCbB9eCBTopqRkI9G1YfCPFbFnTiu6JGbEKWgulXeTWJ9ZtRtJG-ijLMoD1gQeg2g_pi1T7LmCZZDDCY3UpkqOxpGZQhCoAYu4w=s1000', 'story', 'Business Day', 'bloomberg.com', 'Experts warn that protective bubbles, like the one Australia has created, are unsustainable', 'https://www.businesslive.co.za/bd/world/2021-06-03-covid-zero-countries-urged-to-increase-vaccinations-to-avoid-being-hermit-states/', 'Melbourne/Tokyo Covid zero countries that used strict border controls to keep the coronavirus largely at bay for more than a year risk being stuck in limbo and increasingly isolated unless vaccinatio… [+3387 chars]', 'Covid-zero countries urged to increase vaccinations to avoid being ‘hermit’ states - Business Day', '2021-06-03', '07:02:20'),
('6595303', 0, 'https://cdn.24.co.za/files/Cms/General/d/11233/44cb6b45c52d46408960c4c3d115c1e5.jpg', 'story', 'News24', 'Bhekisisa team', 'The stop-start nature of South Africa’s roll-out is not the only reason herd immunity is an unrealistic goal for this year. Find out more.', 'https://www.news24.com/health24/medical/infectious-diseases/coronavirus/sa-is-not-reaching-herd-immunity-our-new-goal-is-containment-heres-how-it-works-20210603-2', '<ul><li>South Africa was aiming to immunise 41-million people by the end of the year in order to reach herd immunity, the point at which Covid-19 was no longer spreading.</li><li>But this level of co… [+13389 chars]', 'SA is not reaching herd immunity. Our new goal is containment – here’s how it works. - News24', '2021-06-03', '10:01:28'),
('6612367', 0, 'https://cdn.24.co.za/files/Cms/General/d/11044/2e8946cd787b478a84a8bb9606b23694.jpg', 'story', 'News24', 'Baden Gillion', 'A rejuvenated Kaizer Chiefs pulled off a dramatic comeback win over Golden Arrows thanks to a sensational Lebogang Manyama hat-trick on Wednesday.', 'https://www.news24.com/sport/soccer/psl/sensational-manyama-hat-trick-keeps-kaizer-chiefs-top-8-hopes-alive-leopards-relegated-20210602', 'A rejuvenated Kaizer Chiefs pulled off a dramatic 3-2 comeback win over Golden Arrows in Soweto thanks to a sensational Lebogang Manyama hat-trick to keep their top 8 hopes alive on Wednesday.\r\nThe r… [+2204 chars]', 'Sensational Manyama hat-trick keeps Kaizer Chiefs` Top 8 hopes alive, Leopards relegated - News24', '2021-06-02', '05:15:57');
INSERT INTO `newsdb` (`item_id`, `view_count`, `img`, `item_type`, `source`, `author`, `descr`, `url`, `content`, `title`, `date_uploaded`, `time_uploaded`) VALUES
('6621940', 0, 'https://lh3.googleusercontent.com/EntmmjetSsYqBlHGTaOh5KK4pELk8NwL4Fvb7ktGhpfGENEg22KHpVeqLkULbXPD-lgMjYi0WSZX_a5D5o1OVIJcpqkUHKKakspVnr7GHVleeA=s1000', 'story', 'TimesLIVE', 'Cebelihle Bhengu', 'The DA said on Wednesday it would lay a criminal charge against the embattled minister.', 'https://www.timeslive.co.za/politics/2021-06-03-da-to-lay-criminal-charges-against-zweli-mkhize-for-his-alleged-conduct-in-digital-vibes-scandal/', '', 'DA to lay criminal charges against Zweli Mkhize for his alleged conduct in Digital Vibes scandal - TimesLIVE', '2021-06-03', '05:40:00'),
('667483', 12, 'https://www.ctvnews.ca/polopoly_fs/1.5449305.1622451268!/httpImage/image.jpg_gen/derivatives/landscape_620/image.jpg', 'story', 'Ctvnews.ca', 'Joe Mcdonald', 'China`s ruling Communist Party said Monday it will ease birth limits to allow all couples to have three children instead of two in hopes of slowing the rapid aging of its population, which is adding to strains on the economy and society.', 'https://www.ctvnews.ca/world/china-easing-birth-limits-further-to-cope-with-aging-society-1.5449304', 'BEIJING -- \r\nChina`s ruling Communist Party said Monday it will ease birth limits to allow all couples to have three children instead of two in hopes of slowing the rapid aging of its population, whi… [+4368 chars]', 'China easing birth limits further to cope with aging society - CTV News', '2021-05-30', '03:42:02'),
('7048907', 0, 'https://www.ctvnews.ca/polopoly_fs/1.5448778.1622396891!/httpImage/image.png_gen/derivatives/landscape_620/image.png', 'story', 'Ctvnews.ca', '', 'Two days after the remains of 215 children were found buried near a former residential school in Kamloops, B.C., the country is making small steps to acknowledge the enormity of the horrific discovery, including the federal government announcing it would be l…', 'https://www.ctvnews.ca/canada/tiny-shoes-and-lowered-flags-memorials-spread-for-215-first-nations-children-found-buried-in-mass-grave-in-b-c-1.5448699', '', 'Tiny shoes and lowered flags: Memorials spread for 215 First Nations children found buried in mass grave in B.C. - CTV News', '2021-05-31', '03:42:03'),
('7059441', 0, 'https://www.straight.com/files/v3/styles/gs_feature/public/images/21/05/51215680462_83e2326489_c.jpg?itok=Wk7sABFv', 'story', 'Straight.com', '', 'A total of 12 children received the Moderna vaccine by mistake.', 'https://www.straight.com/covid-19-pandemic/may-31-coronavirus-update-bc-vancouver-vaccine-error-among-youth-recipients-one-new-bloodclotting-case-and-more', 'With B.C.s reopening plan underway, this week, as B.C. provincial health officer Dr. Bonnie Henry noted at todays briefing, B.C. will begin to see any cases that may have been contracted among those … [+7137 chars]', 'COVID-19 in B.C.: Vaccine error among youth; one new blood-clot case; outbreak at one school; and more - The Georgia Straight', '2021-06-01', '12:50:00'),
('7080354', 0, 'https://img.buzzfeed.com/buzzfeed-static/static/2021-05/31/3/campaign_images/976d68fe3db8/what-will-we-do-without-mare-of-easttown-2-3868-1622430478-8_dblbig.jpg?resize=1200:*', 'story', 'BuzzFeed News', 'Estelle Tang', 'The HBO whodunit replaced the Sunday scaries with prime appointment TV. Here’s why it worked so well.', 'https://www.buzzfeednews.com/article/estelletang/mare-of-easttown-finale-season-1-review', 'On Sunday night, HBO crime drama Mare of Easttown came to an end. Boasting Kate Winslet in the title role, twisty plotlines, and breakneck pacing, the series earned fans aplenty over the course of it… [+15777 chars]', 'What Will We Do Without ``Mare Of Easttown``? - BuzzFeed News', '2021-05-31', '03:42:02'),
('7108878', 0, 'https://smartcdn.prod.postmedia.digital/vancouversun/wp-content/uploads/2021/05/health-coronavirus-waiver-stocks.jpg', 'story', 'Vancouver Sun', 'The Canadian Press', 'The health authority says the errors happened Friday and Saturday during the first full week that kids aged 12 to 17 could get their first dose.', 'https://vancouversun.com/news/local-news/a-dozen-kids-mistakenly-given-the-wrong-covid-19-vaccine-in-vancouver', 'Article content\r\nVancouver Coastal Health is apologizing and says its updating its immunization processes after confirming a dozen incidents in which youth were given the wrong COVID-19 vaccine.\r\nThe… [+2201 chars]', 'COVID-19: A dozen kids mistakenly given the wrong vaccine in Vancouver - Vancouver Sun', '2021-06-01', '12:33:45'),
('718678', 0, 'https://www.dailymaverick.co.za/wp-content/uploads/2021/06/BM-Sasha-BurgerKing-option-1.jpg', 'story', 'Daily Maverick', 'Sasha Planting', 'The sale of Burger King to a pan-African private equity firm has been blocked by the regulator because it cannot be justified on public interest grounds. There are no competition issues.', 'https://www.dailymaverick.co.za/article/2021-06-02-bee-credentials-lacking-competition-commission-deals-a-blow-to-gpi-and-its-long-suffering-shareholders/', '(Photo: Gallo Images / Misha Jordaan) \r\nThe Competition Commission has prohibited the sale of the Burger King chain of restaurants to private equity firm Emerging Capital Partners for R570-million be… [+4043 chars]', 'BEE credentials lacking: Competition Commission deals a blow to GPI and its long-suffering shareholders - Daily Maverick', '2021-06-02', '07:20:36'),
('7566023', 0, 'http://cdn.primedia.co.za/primedia-broadcasting/image/upload/c_fill,h_437,w_700/d6csriycchgxr9mrmrln', 'story', 'EWN', 'Nkosikhona Duma', 'Former President Jacob Zuma has challenged State prosecutor Advocate Billy Downer’s right to prosecute him by a special plea application in terms of Section 106 of the Criminal Procedure Act.', 'https://ewn.co.za/2021/06/03/downer-dismisses-zuma-argument-over-his-competency-to-prosecute-corruption-case', 'Former President Jacob Zuma has challenged State prosecutor Advocate Billy Downer’s right to prosecute him by a special plea application in terms of Section 106 of the Criminal Procedure Act.\r\n DURBA… [+1696 chars]', 'Downer dismisses Zuma argument over his competency to prosecute corruption case - Eyewitness News', '2021-06-03', '05:11:27'),
('7728984', 0, 'http://www.bnnbloomberg.ca/polopoly_fs/1.1611541!/fileimage/httpImage/image.jpg_gen/derivatives/landscape_620/signage-outside-an-amc-movie-theater-in-new-york-u-s-on-friday-march-5-2021-the-struggling-u-s-box-office-is-expected-to-rebound-this-weekend-when-theaters-in-new-york-city-the-second-largest-u-s-movie-market-reopen-after-a-yearlong-hiatus-photographer-amir-hamja-bloomberg.jpg', 'story', 'BNNBloomberg.ca', 'Bloomberg News', 'AMC Entertainment Holdings Inc. is really leaning into this whole meme-stock phenomenon.', 'http://www.bnnbloomberg.ca/amc-extends-advance-in-premarket-trading-on-mudrick-deal-1.1611540', 'AMC Entertainment Holdings Inc. is really leaning into this whole meme-stock phenomenon.\r\nOn Wednesday, the movie-theater chain announced that it would reward small-time investors, who have been inst… [+3265 chars]', 'AMC extends advance in premarket trading on Mudrick deal - BNN', '2021-06-02', '09:47:25'),
('7847637', 12, 'https://www.vmcdn.ca/f/files/shared/feeds/cp/2021/05/20210530220540-60b44cb004e8b3fdfb8303e0jpeg.jpg;w=650;h=466;mode=crop', 'story', 'Dawson Creek Mirror', 'Canadian Press', 'The latest numbers on COVID-19 vaccinations in Canada as of 4:00 a.m. ET on Monday May 31, 2021. In Canada, the provinces are reporting 315,187 new vaccinations administered for a total of 23,471,446 doses given. Nationwide, 2,012,849 people or 5.', 'https://www.dawsoncreekmirror.ca/national-news/a-look-at-covid-19-vaccinations-in-canada-on-may-31-2021-3824140', 'The latest numbers on COVID-19 vaccinations in Canada as of 4:00 a.m. ET on Monday May 31, 2021.\r\nIn Canada, the provinces are reporting 315,187 new vaccinations administered for a total of 23,471,44… [+8192 chars]', 'A look at COVID-19 vaccinations in Canada on May 30, 2021 - Dawson Creek Mirror', '2021-05-31', '03:42:02'),
('7855463', 0, 'https://images.hgmsites.net/hug/toyota-tacoma_100793690_h.jpg', 'story', 'Motor Authority', 'Viknesh Vijayenthiran', 'Toyota`s off-road-ready Tacoma Trail Edition and TRD Pro come with even more standard features for 2022.', 'https://www.motorauthority.com/news/1132444_2022-toyota-tacoma-trail-edition-and-trd-pro-revealed-with-fresh-updates', 'Toyota is continuing its practice of introducing running updates to the off-road-ready versions of its Tacoma mid-size pickup truck, which for 2022 include the Trail Edition and TRD Pro.\r\nThe Tacoma … [+1729 chars]', '2022 Toyota Tacoma Trail Edition and TRD Pro revealed with fresh updates - Motor Authority', '2021-06-02', '11:00:00'),
('7896753', 0, 'https://ml.globenewswire.com/Resource/Download/9782a337-07ac-424b-9c5a-f9cde47d8d55?size=1', 'story', 'GlobeNewswire', 'Advanced Micro Devices, Inc.', '— Keynote highlights company’s growing momentum, strong and expanding set of partners, and breakthrough AMD technologies powering gaming, PCs and the...', 'https://www.globenewswire.com/news-release/2021/06/01/2239108/0/en/AMD-Showcases-Industry-Leading-Innovation-Across-the-High-Performance-Computing-Ecosystem-at-COMPUTEX-2021.html', 'Keynote highlights companys growing momentum, strong and expanding set of partners, and breakthrough AMD technologies powering gaming, PCs and the data center \r\nSANTA CLARA, Calif., May 31, 2021 (GLO… [+14044 chars]', 'AMD Showcases Industry-Leading Innovation Across the High-Performance Computing Ecosystem at COMPUTEX 2021 - GlobeNewswire', '2021-06-01', '03:00:00'),
('7901688', 0, 'https://www.theglobeandmail.com/resizer/0W-UOwbjt6kewEXxJ0tZ-VMipvY=/1200x0/filters:quality(80)/cloudfront-us-east-1.images.arcpublishing.com/tgam/26GE2GC2SRCSZKB7Y4T6XLBY7A.jpg', 'story', 'The Globe And Mail', 'Leslie Beck', 'Findings from a four-year randomized controlled trial indicate that the combination of healthy eating and regular aerobic exercise improves cognitive prowess in middle-aged and older adults', 'https://www.theglobeandmail.com/life/health-and-fitness/article-a-healthy-diet-plus-aerobic-exercise-preserves-cognition/', 'Findings from a four-year randomized controlled trial indicate that the combination of healthy eating and regular aerobic exercise improves cognitive prowess in middle-aged and older adults.\r\nISTOCKP… [+4820 chars]', 'A healthy diet plus aerobic exercise preserves cognition - The Globe and Mail', '2021-05-31', '03:42:01'),
('7915291', 0, 'https://mk0globalbankin3xg02.kinstacdn.com/wp-content/uploads/2021/06/HUAWEI-TECH-SMARTPHONE.jpg', 'story', 'Global Banking And Finance Review', '', 'By David Kirton SHENZHEN, China (Reuters) – China’s Huawei Technologies launched its Harmony operating system for smartphones on Wednesday, looking to recover from U.S. sanctions that have hobbled its handset business. Huawei will start rolling out HarmonyOS …', 'https://www.globalbankingandfinance.com/huawei-launches-new-operating-system-for-phones-eyes-internet-of-things-market/', 'By David Kirton\r\nSHENZHEN, China (Reuters) – China’s Huawei Technologies launched its Harmony operating system for smartphones on Wednesday, looking to recover from U.S. sanctions that have hobbled i… [+3314 chars]', 'Huawei launches new operating system for phones, eyes `Internet-of-Things` market - Global Banking And Finance Review', '2021-06-03', '09:00:26'),
('8107937', 0, 'https://www.dailymaverick.co.za/wp-content/uploads/2021/06/BM-Tim-AyoBT-option-1.jpg', 'story', 'Daily Maverick', 'Tim Cohen', 'British telecoms giant BT has announced it intends terminating its relationship with the Sekunjalo Group, revealing the identity of the ‘large client’ which plunged associated company Ayo into a loss when it recently announced its interim results.', 'https://www.dailymaverick.co.za/article/2021-06-02-british-telecoms-giant-bt-to-end-relationship-with-surves-sekunjalo-group/', 'Sekunjalo Group executive chairman Iqbal Survé. (Photo: Gallo Images / Wessel Oosthuizen) \r\nThe cat is out of the bag about the identity of what controversial IT group Ayo Technology Solutions descri… [+3640 chars]', 'British telecoms giant BT to end relationship with Survé’s Sekunjalo Group - Daily Maverick', '2021-06-02', '07:06:13'),
('8122061', 0, 'https://i.cbc.ca/1.5520668.1621648866!/fileImage/httpImage/image.jpeg_gen/derivatives/16x9_620/amazon-warehouse-ottawa.jpeg', 'story', 'CBC News', '', 'An Amazon employee says working at the distribution giant’s Ottawa warehouse during the pandemic has been a nerve-racking experience, saying some safety measures have been ignored and dozens of workers have tested positive.', 'https://www.cbc.ca/news/canada/ottawa/ottawa-amazon-warehouse-covid-19-1.6024241', 'An Amazon employee says working at the distribution giant`s Ottawa warehouse during the pandemic has been a nerve-racking experience, citing examples of safety measures that were allegedly ignored an… [+6529 chars]', '`Terrified` Amazon employee speaks out about lax COVID-19 precautions - CBC.ca', '2021-05-31', '03:42:01'),
('8187276', 0, 'https://cdn.24.co.za/files/Cms/General/d/11233/cfb97237a8cc4da6a5291912d03b9fa3.jpg', 'story', 'News24', 'Baden Gillion', 'Club legend Arthur Zwane said he was both ``thankful`` and ``feeling privileged`` to be part of the Kaizer Chiefs family after securing his first win as caretaker coach over Golden Arrows on Wednesday.', 'https://www.news24.com/sport/soccer/psl/club-legend-arthur-zwane-feeling-privileged-after-first-kaizer-chiefs-win-as-head-coach-20210602', 'Club legend Arthur Zwane said he was both ``thankful`` and ``feeling privileged`` to be part of the Kaizer Chiefs family after securing his first win as caretaker coach over Golden Arrows on Wednesday. \r… [+1951 chars]', 'Club legend Arthur Zwane feeling `privileged` after first Kaizer Chiefs win as head coach - News24', '2021-06-02', '07:07:30'),
('8285713', 1, 'https://cdn.24.co.za/files/Cms/General/d/10127/c7285e55f3b44e6ab2f25d12e7ff6f6e.jpg', 'story', 'News24', 'Compiled by Stefni Herbert', 'If you are sleep-deprived and think that chugging coffee will carry you through the day, you may be mistaken.', 'https://www.news24.com/health24/medical/sleep/news/coffee-may-not-help-the-sleep-deprived-as-much-as-people-believe-20210603-3', '<ul><li>A study has found that if you`re sleep-deprived, caffeine can only do so much for you</li><li>Researchers investigated the sleep-deprived brain </li><li>Participants were given either caffein… [+3990 chars]', 'Coffee may not help the sleep-deprived as much as people believe - News24', '2021-06-03', '03:34:21'),
('8321082', 0, 'https://assets.stockhouse.com/kentico-cms/0251-00/images/stockhouse-logo-og.png', 'story', 'Stockhouse', 'Stockhouse.com', 'NVIDIA RTX Titles Jump to 130 on Widespread Industry Adoption of Ray Tracing, NVIDIA DLSS', 'https://stockhouse.com/news/press-releases/2021/06/01/nvidia-rtx-titles-jump-to-130-on-widespread-industry-adoption-xa0-of-ray', '‘DOOM Eternal&amp;CloseCurlyQuote;, ‘Rainbow Six Siege&amp;CloseCurlyQuote; and ‘Red Dead Redemption 2&amp;CloseCurlyQuote; Among Latest RTX Titles; NVIDIA Reflex in 12 of Top 15 Competitive Shooters… [+9721 chars]', 'NVIDIA RTX Titles Jump to 130 on Widespread Industry Adoption of Ray Tracing, NVIDIA DLSS - Stockhouse', '2021-06-01', '05:11:00'),
('8338133', 0, 'https://lh3.googleusercontent.com/iuc9tocK2qe_Kt0GRt2U9OC98UCAQTprjEOh93BixPr9Jrmxom6OgMnSSxnYtdh4en6z5iz11p2tZmMn3Vp5vOCbccwuP2VyCok=s1000', 'story', 'SowetanLIVE', 'Ernest Mabuza', 'The special plea by former president Jacob Zuma wanting the removal of Billy Downer as prosecutor in his corruption trial should be rejected, says the state.', 'https://www.sowetanlive.co.za/news/south-africa/2021-06-02-billy-downer-opposes-bid-by-jacob-zuma-to-remove-him-as-prosecutor/', '', 'Billy Downer opposes bid by Jacob Zuma to remove him as prosecutor - SowetanLIVE', '2021-06-02', '03:43:49'),
('8441143', 0, 'https://techcentral.co.za/wp-content/uploads/2021/03/eskom-2156-1120.jpg', 'story', 'TechCentral', 'Staff Reporter', 'While implementing countrywide blackouts this week, energy regulator Nersa has published for comment Eskom’s latest submission for additional revenue to be recovered from electricity tariffs.', 'https://techcentral.co.za/eskom-seeks-billions-more-from-south-african-consumers/107769/', 'While subjecting households and businesses countrywide to rotating blackouts this week, energy regulator Nersa has published for comment Eskoms latest submission for additional revenue to be recovere… [+4749 chars]', 'Eskom seeks billions more from South African consumers - TechCentral', '2021-06-03', '06:57:38'),
('8509736', 0, 'https://i.cbc.ca/1.6046318.1622407204!/fileImage/httpImage/image.JPG_gen/derivatives/16x9_620/israel-politics.JPG', 'story', 'CBC News', '', 'On Sunday, right-wing nationalist party leader Naftali Bennett announced a deal with centrist Yair Lapid to form a new `unity government` to end the political upheaval in Israel. If successful, it would mark the end of Benjamin Netanyahu`s current 12-year run…', 'https://www.cbc.ca/news/world/israel-netanyahu-coalition-government-1.6046255', 'A flurry of promises, backroom deal-making and last-minute shifts in political allegiance marked what seems to be the final days of Benjamin Netanyahu`s long tenure as prime minister of Israel.\r\nWhen… [+6764 chars]', 'Benjamin Netanyahu`s days leading Israel could be numbered as new coalition forms - CBC.ca', '2021-05-31', '03:42:02'),
('8576781', 0, 'https://www.aljazeera.com/wp-content/uploads/2021/06/hua.jpg?resize=1200%2C630', 'story', 'Al Jazeera English', 'Al Jazeera', 'The launch of the operating system comes as Huawei is still cut off from US technologies including Google’s services.', 'https://www.aljazeera.com/economy/2021/6/2/huawei-launches-its-own-mobile-operating-system-on-handsets', 'Huawei launched its own HarmonyOS mobile operating system on its handsets on Wednesday as it adapts to having lost access to Google mobile services two years ago after the United States put the Chine… [+4082 chars]', 'Huawei launches its own mobile operating system on handsets - Al Jazeera English', '2021-06-02', '04:54:57'),
('8706152', 0, 'https://cdn.24.co.za/files/Cms/General/d/10839/06cab01c66a04daeb4f63ae66dab7a72.jpg', 'story', 'News24', 'Khanyiso Tshwaku', 'That Devon Conway is playing Test cricket and cracked a maiden ton on debut against England on the first day of the first Test at Lords shouldn`t come as a surprise.', 'https://www.news24.com/sport/cricket/who-is-new-blacks-caps-star-devon-conway-and-how-was-he-lost-to-sa-cricket-20210603', '<ul><li>New Zealand`s Devon Conway is the latest South African to make an impact on the international stage, but not for the Proteas.</li><li>The 29-year-old from Johannesburg made an unbeaten ton on… [+3391 chars]', 'Who is new Blacks Caps star Devon Conway, and how was he lost to SA cricket? - News24', '2021-06-03', '09:17:51'),
('8762316', 0, 'https://globalnews.ca/wp-content/uploads/2021/06/canadarm2-e1622642783441.jpg?quality=85&strip=all&w=720&h=379&crop=1', 'story', 'Global News', 'joshkelliott', 'Speeding space junk punched a hole through the International Space Station`s robotic arm, the CSA says.', 'https://globalnews.ca/news/7913922/canadarm2-damaged-international-space-station-junk/', 'A piece of space debris struck the International Space Station (ISS) and damaged its robotic Canadarm2 sometime last month, according to Canadian officials.\r\nThankfully, the damage wasn’t enough to s… [+2171 chars]', 'Canadarm2 damaged by ‘lucky strike’ from space junk in orbit - Global News', '2021-06-02', '02:21:44'),
('8783947', 0, 'https://cdn.24.co.za/files/Cms/General/d/11233/11ec19c810b547b8ba25e94e60b963d2.jpg', 'story', 'News24', 'sport', 'Devon Conway became just the sixth batsman to score a hundred on Test debut at Lord`s to leave New Zealand well-placed at stumps on the first day of their series opener against England.', 'https://www.news24.com/sport/cricket/south-african-born-devon-conway-hits-ton-on-test-debut-to-put-new-zealand-on-top-against-england-20210602', 'South African born Devon Conway became just the sixth batsman to score a hundred on Test debut at Lord`s to leave New Zealand well-placed at stumps on the first day of their series opener against Eng… [+3236 chars]', 'South African-born Devon Conway hits ton on Test debut to put New Zealand on top against England - News24', '2021-06-02', '06:56:56'),
('8811567', 0, 'https://www.ctvnews.ca/polopoly_fs/1.5307810.1613192243!/httpImage/image.jpg_gen/derivatives/landscape_620/image.jpg', 'story', 'Ctvnews.ca', 'Lee Berthiaume', 'Canada is set to receive 2.9 million COVID-19 vaccine doses this week thanks in large part to an increase in planned deliveries from Pfizer and BioNTech.', 'https://www.ctvnews.ca/health/coronavirus/canada-to-receive-2-9m-vaccine-doses-this-week-as-pfizer-biontech-increase-deliveries-1.5449303', 'OTTAWA -- \r\nCanada is set to receive 2.9 million COVID-19 vaccine doses this week thanks in large part to an increase in planned deliveries from Pfizer and BioNTech.\r\nThe two pharmaceutical companies… [+2566 chars]', 'Canada to receive 2.9M vaccine doses this week as Pfizer-BioNTech increase deliveries - CTV News', '2021-05-31', '03:42:02'),
('8820089', 0, 'https://www.ctvnews.ca/polopoly_fs/1.5423464.1620766906!/httpImage/image.jpg_gen/derivatives/landscape_620/image.jpg', 'story', 'Ctvnews.ca', '', 'Britain will celebrate Queen Elizabeth`s 70 years on the throne with four days of festivities beginning with her ceremonial birthday parade on June 2, 2022.', 'https://www.ctvnews.ca/world/u-k-to-mark-queen-s-platinum-jubilee-with-4-days-of-events-1.5452667', 'LONDON -- \r\nBritain will celebrate Queen Elizabeth II`s 70 years on the throne with four days of festivities beginning with her ceremonial birthday parade on June 2, 2022.\r\nBuckingham Palace on Wedne… [+832 chars]', 'U.K. to mark Queen`s Platinum Jubilee with 4 days of events - CTV News', '2021-06-02', '11:41:00'),
('8925619', 0, 'http://www.bnnbloomberg.ca/img/tsn/logos/tsn-logo.png', 'story', 'BNNBloomberg.ca', 'Bloomberg News', 'Wells in the energy-rich region release three times as much of the potent greenhouse gas as wells in California, according to NASA-led research.', 'http://www.bnnbloomberg.ca/permian-study-finds-overproduction-leading-to-more-methane-leaks-1.1611596', '(Bloomberg) -- The energy-rich region of the southwestern U.S. known to geologists and fossil fuel enthusiasts as the Permian Basin has expanded its production more quickly than any other oil and gas… [+3556 chars]', 'Permian Study Finds Overproduction Leading to More Methane Leaks - BNN', '2021-06-02', '12:17:24'),
('9071124', 0, 'https://www.theglobeandmail.com/resizer/H-6YYY8VALbncJftY4xghtN1m90=/1200x0/filters:quality(80)/cloudfront-us-east-1.images.arcpublishing.com/tgam/TKPVTEQUQFN47EZAB7ISSEQZBI.jpg', 'story', 'The Globe And Mail', '', 'Vaccinating at least 90 per cent of eligible Canadians against COVID-19 could tip the balance against new, more infectious variants much better than the 75-per-cent uptake Ottawa is pushing for. Here’s how things could play out', 'https://www.theglobeandmail.com/canada/article-how-many-doses-will-make-the-difference-between-a-canadian-fourth-wave/', 'Femia Gabiana, a licensed practical nurse at B.C.`s Fraser Health region, administers a first dose of Pfizer vaccine at a walk-in vaccination clinic at Bear Creek Park in Surrey, B.C.\r\nDarryl Dyck/Th… [+13580 chars]', 'How many COVID-19 vaccine doses could make the difference between a fourth wave in Canada and no wave at all? New models offer four scenarios - The Globe and Mail', '2021-05-31', '03:42:02'),
('9322326', 0, 'https://mybroadband.co.za/news/wp-content/uploads/2021/06/Jail.jpg', 'story', 'MyBroadband', 'https://www.facebook.com/mybroadband', 'President Cyril Ramaphosa signed the Cybercrimes Act into law on Tuesday, which has made it a criminal offence to circulate certain types of harmful messages on social media.', 'https://mybroadband.co.za/news/technology/399979-three-types-of-whatsapp-messages-can-now-land-you-in-jail-in-south-africa.html', 'President Cyril Ramaphosa signed the Cybercrimes Act into law on Tuesday, introducing new laws that criminalise the sending of certain types of harmful messages on social media in South Africa.\r\nPena… [+3828 chars]', 'Three types of WhatsApp messages can now land you in jail in South Africa - MyBroadband', '2021-06-03', '05:03:00'),
('9361591', 1, 'https://www.theglobeandmail.com/resizer/OYMu5IuLzkgCeo8O5kBCZbIY8KM=/1200x0/filters:quality(80)/cloudfront-us-east-1.images.arcpublishing.com/tgam/BYRGC4M5RZHWTBXNHBGGNZAM64.jpg', 'story', 'The Globe And Mail', '', 'In a season full of promise, Toronto’s playoff woes carry on for another year courtesy of a first round exit against the Montreal Canadiens', 'https://www.theglobeandmail.com/sports/article-canadiens-advance-maple-leafs-fall-in-game-7-again-as-history-repeats/', 'Jake Evans (71) of the Montreal Canadiens skates the puck ahead of Auston Matthews (34) of the Toronto Maple Leafs during Game 7 at Scotiabank Arena on May 31, 2021 in Toronto, Ont.\r\nClaus Andersen/G… [+5202 chars]', 'Canadiens advance, Maple Leafs fall in Game 7 again as history repeats itself - The Globe and Mail', '2021-06-01', '02:22:47'),
('9377450', 5, '', 'story', 'Google News', '', '', 'https://news.google.com/__i/rss/rd/articles/CBMieWh0dHBzOi8vd3d3LnNwYWNlZmxpZ2h0aW5zaWRlci5jb20vbWlzc2lvbnMvc29sYXItc3lzdGVtL25hc2EtcmVsZWFzZXMtM2QtdmlkZW8tb2YtaW5nZW51aXR5LW1hcnMtaGVsaWNvcHRlcnMtM3JkLWZsaWdodC_SAQA?oc=5', '', 'NASA releases 3D video of Ingenuity Mars Helicopter`s 3rd flight - SpaceFlight Insider', '2021-06-01', '01:54:46'),
('9414896', 0, 'https://i.cbc.ca/1.6044786.1622241551!/fileImage/httpImage/image.jpeg_gen/derivatives/16x9_620/tom-puglas.jpeg', 'story', 'CBC News', '', 'Tom Puglas, a First Nations elder on Vancouver Island, says he planned to repair his aging boat. But before he could — and without any warning, he says — the coast guard destroyed the boat, which it says was sinking and leaching oil. Now, a federal agency wan…', 'https://www.cbc.ca/news/indigenous/boat-destoryed-elder-1.6044730', 'Tom Puglas, 76, says he had just spent thousands of dollars on parts to fix the engine of his aging, second-hand fishing boat when he received a phone call from a friend in the fall of 2017 telling h… [+5630 chars]', 'The coast guard destroyed his boat without asking. Now, a federal agency wants him to pay $8,500 bill - CBC.ca', '2021-05-31', '03:42:02'),
('9479095', 0, 'https://cdn.24.co.za/files/Cms/General/d/11232/4fa1066051b649958b90c419e634c834.jpeg', 'story', 'News24', 'amaBhungane reporters', 'Two senior officials at the minerals and energy department have filed affidavits confirming a meeting with gas-to-power entrepreneur Aldworth Mbalati at an upmarket restaurant in Pretoria. But they dispute Mbalati`s claim they pressured him to engage in a cor…', 'https://www.news24.com/fin24/companies/powerships-officials-confirm-they-met-bidder-ministers-associates-at-upmarket-restaurant-20210603', '<ul><li>Two senior officials at the minerals and energy department have filed affidavits confirming a meeting with gas-to-power entrepreneur Aldworth Mbalati at an upmarket restaurant in Pretoria.</l… [+11547 chars]', 'Powerships: Officials confirm they met bidder, `minister`s associates` at upmarket restaurant - News24', '2021-06-03', '04:38:42'),
('9662799', 0, 'https://businesstech.co.za/news/wp-content/uploads/2021/01/Brick-wall.jpg', 'story', 'Businesstech.co.za', 'https://www.facebook.com/BusinessTechSA', 'South Africa’s latest unemployment figures are largely in line with expectations, but there are concerns around the country’s slowing absorption and participation rates, say Nedbank economists.', 'https://businesstech.co.za/news/business/495505/south-africa-has-hit-a-jobs-wall-and-it-could-be-around-for-a-while/', 'South Africa’s latest unemployment figures are largely in line with expectations, but there are concerns around the country’s slowing absorption and participation rates, say Nedbank economists.\r\nWhil… [+4334 chars]', 'South Africa has hit a jobs wall – and it could be around for a while - BusinessTech', '2021-06-02', '02:08:17'),
('9699134', 0, 'https://businesstech.co.za/news/wp-content/uploads/2021/02/Money-south-africa-rand.png', 'story', 'Businesstech.co.za', 'https://www.facebook.com/BusinessTechSA', 'The South African rand rallied to its highest level in more than two years against the dollar on Wednesday, as the local currency continued its strong run on the back of a sustained rebound in global economies and US Treasury data.', 'https://businesstech.co.za/news/finance/495721/rand-hits-two-year-high-against-the-dollar-as-it-continues-strong-run/', 'The South African rand rallied to its highest level in more than two years against the dollar on Wednesday, as the local currency continued its strong run on the back of a sustained rebound in global… [+1664 chars]', 'Rand hits two-year high against the dollar as it continues strong run - BusinessTech', '2021-06-03', '07:18:35'),
('9770260', 0, '', 'story', 'The Guardian', 'Guardian staff reporter', 'Government suspends fishing along 50-mile coastline after explosion and fire', 'https://amp.theguardian.com/world/2021/jun/02/cargo-ship-carrying-tonnes-of-chemicals-sinks-off-sri-lanka', 'Sri LankaGovernment suspends fishing along 50-mile coastline after explosion and fire\r\nA cargo ship carrying tonnes of chemicals has sunk off Sri Lankas west coast, and tonnes of plastic pellets have… [+2113 chars]', 'Cargo ship carrying tonnes of chemicals sinks off Sri Lanka - The Guardian', '2021-06-02', '03:37:00'),
('9774387', 0, 'http://www.thesouthafrican.com/wp-content/uploads/2021/05/Thembinkosi_Lorch.jpeg', 'story', 'The South African', 'facebook.com/Soccerzela', 'Follow our special live `goal rush` from this afternoon`s crunch DStv Premiership encounter between Orlando Pirates and Baroka FC below', 'https://www.thesouthafrican.com/sport/soccer/psl-south-africa/orlando-pirates-vs-baroka-live-dstv-premiership-goal-rush/', 'Baroka FC host Orlando Pirates in a crunch DStv Premiership clash this afternoon and you can follow all of the live updates on our Goal Rush below.Orlando Pirates head into today’s clash in fourth pl… [+1397 chars]', 'Orlando Pirates vs Baroka: LIVE DStv Premiership Goal Rush - The South African', '2021-06-02', '02:35:00'),
('9817713', 0, 'https://i.cbc.ca/1.5515904.1585658150!/cpImage/httpImage/image.jpg_gen/derivatives/16x9_620/doug-ford-stephen-lecce-ontario-covid-19.jpg', 'story', 'CBC News', '', 'Ontario Premier Doug Ford and Education Minister Stephen Lecce are expected to make an announcement about whether schools will be reopening to in-person learning for the remainder of the school year this afternoon.', 'https://www.cbc.ca/news/canada/toronto/ford-lecce-school-announcement-1.6049729', 'Ontario Premier Doug Ford will be joined by Minister of Education Stephen Lecce and Health Minister Christine Elliott to make an announcement at 1 p.m. CBC News will carry the news conference live.\r\n… [+886 chars]', 'Ford, Lecce expected to make announcement about Ontario school reopening plan - CBC.ca', '2021-06-02', '01:52:35'),
('9918334', 0, '', 'story', 'Google News', '', '', 'https://news.google.com/__i/rss/rd/articles/CBMiK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9dzhnTXNiYTVlMlHSAQA?oc=5', '', 'COVID:19- Second vaccine dose announcement imminent - Edmonton Journal', '2021-05-31', '09:32:12'),
('9962914', 0, 'https://smartcdn.prod.postmedia.digital/financialpost/wp-content/uploads/2021/06/FP-Feature.png', 'story', 'Financial Post', 'Advertisement', 'Mining exploration is tough at the best of times, but conducting field work during a pandemic can bring progress to a halt.', 'https://financialpost.com/business-trends/why-prospects-of-a-new-discovery-put-pan-global-resources-at-the-forefront-of-the-copper-space', 'This article is Advertised by Market One Media Group\r\nThis Vancouver-based junior mining company overcame COVID-19 challenges and is ``hitting copper with every hole`` \r\nAdvertisement\r\nDrilling at the … [+12925 chars]', 'Why prospects of a new discovery put Pan Global Resources at the forefront of the copper space - Regina Leader-Post', '2021-06-02', '04:07:13');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `firstname` text NOT NULL,
  `lastname` text NOT NULL,
  `password` varchar(500) NOT NULL,
  `isadmin` int(1) NOT NULL,
  `isloggedin` int(1) NOT NULL,
  `about` text NOT NULL,
  `time_reg` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `firstname`, `lastname`, `password`, `isadmin`, `isloggedin`, `about`, `time_reg`) VALUES
(1, 'abc@gmail.com', 'bbb', 'kjnkjnjk', 'ef51306214d9a6361ee1d5b452e6d2bb70dc7ebb85bf9e02c3d4747fb57d6bec', 0, 1, '0', '2021-05-30 20:57:09'),
(2, 'admin@gmail.com', 'aa', 'aa', '5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5', 0, 1, '0', '2021-05-30 20:59:51'),
(3, '123@gmail.com', '123', 'qwe', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', 0, 0, '0', '2021-05-30 21:01:34'),
(4, 'akahle@gmail.com', 'akahle', 'man', 'eebe8b5af6d2d5536e3cca806887b5428d44b9dde64428177942e33c3d2b8de9', 0, 1, '0', '2021-06-01 12:44:07');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `loginattempt`
--
ALTER TABLE `loginattempt`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `newsdb`
--
ALTER TABLE `newsdb`
  ADD PRIMARY KEY (`item_id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `loginattempt`
--
ALTER TABLE `loginattempt`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
